### Listar materias
GET http://127.0.0.1:8000/materias?inicio=0&cantidad=2

### Buscar materia
GET http://127.0.0.1:8000/materias/2?detalle=Materia seleccionada

### Alumno y materia
GET http://127.0.0.1:8000/alumnos/10/materias/3?observacion=Regular&completo=true