### Crear producto
POST http://127.0.0.1:8000/productos
Content-Type: application/json

{
    "nombre": "Auriculares",
    "precio": 45000,
    "stock": 8
}

### Buscar producto
GET http://127.0.0.1:8000/buscar?nombre=Auriculares&precio_maximo=50000