### Crear alumno
POST http://127.0.0.1:8000/alumnos
Content-Type: application/json

{
    "nombre": "Lucia",
    "edad": 21,
    "carrera": "Informatica"
}

### Actualizar alumno
PUT http://127.0.0.1:8000/alumnos/1
Content-Type: application/json

{
    "nombre": "Lucia",
    "edad": 22,
    "carrera": "Informatica"
}